
services:
  postgres:
    image: postgres:latest
    container_name: criff_postgres
    restart: always
    environment:
      POSTGRES_DB: criff_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - criff_network

volumes:
  postgres_data:

networks:
  criff_network:
    driver: bridge
